Fixed compilation for ES5 target
notenoughneon/typed-promisify pull request #1
Opened 2017-01-25 17:37 UTC by nahuel

When the TS compilation target is `es5` (as in `tsc --target es5 --lib es5,es2015.promise xxx.ts`), `tsc` outputs the following errors:

```
node_modules/typed-promisify/index.ts(10,51): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
node_modules/typed-promisify/index.ts(36,51): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
```

This PR fixes that.

2017-01-26 00:25 UTC, notenoughneon requested changes
Changing the arrow functions to functions broke the tests. Can you try the alternate solution I suggested?

More info on this here: https://github.com/Microsoft/TypeScript/issues/1609

2017-01-26 00:25 UTC, notenoughneon commented on index.ts
>              var args = Array.prototype.slice.call(arguments);
Try moving this line to the enclosing function (line 8).

2017-01-26 00:25 UTC, notenoughneon commented on index.ts
>              var args = Array.prototype.slice.call(arguments);
Same with this one.

2017-01-26 02:09 UTC, nahuel commented
Sorry, you are right.

2017-01-26 03:03 UTC, nahuel commented
changed PR to https://github.com/nahuel/typed-promisify/commit/008d4775c99375124e8d9e468c431a9a27d29328

2017-01-27 06:06 UTC, notenoughneon commented
I merged https://github.com/notenoughneon/typed-promisify/pull/3 which also included the same fix. Sorry to make you go to extra effort.

2017-01-27 06:06 UTC, closed without merging